Devo theme
DevoInc/devoinc.github.io pull request #1
Opened 2021-04-13 16:54 UTC by albertocollado

Devo Engineering Blog: Devo theme developed (alpha version)

2021-04-13 16:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DevoInc/devoinc.github.io?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DevoInc/devoinc.github.io?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DevoInc/devoinc.github.io?pullRequest=1) it.</sub>

2021-04-15 13:15 UTC, tripu requested changes
It looks great! Good job!

Just a suggestion.

The width available to actual content on a wide screen is kind of narrow, I think. If we were planning to share regular prose it wouldn't be a problem. But given that we will have snippets of code, commands, tables, diagrams, charts&hellip; it's a pity not being able to stretch things horizontally a bit more. I fear we will have horizontal scroll bars too often, when they should not be necessary.

Paradoxically, and because of the media queries, shrinking the window gets you to a point where the sidebar collapses and the `<article>` suddenly becomes _wider_. Right there it looks more legible to me.

I think that specific breakpoint is in line `1025` of `/assets/css/main.css` (not sure where's the actual source, though):

```css
@media (min-width: 64em) { .page { float: right; width: calc(100% - 200px); padding-right: 200px; } }
```

2021-04-15 13:15 UTC, tripu commented on _posts/2013-08-16-markup-syntax-highlighting.md
> +  teaser: "assets/images/devo-theme/hero_bg.jpg"
```suggestion
  teaser: "/assets/images/devo-theme/hero_bg.jpg"
```

2021-04-15 13:17 UTC, tripu commented on _posts/2013-08-16-markup-syntax-highlighting.md
> +  teaser: "assets/images/devo-theme/hero_bg.jpg"
(This is not important, because the post is just a placeholder, of course. FYI only.)

2021-04-16 08:01 UTC, albertocollado commented on _posts/2013-08-16-markup-syntax-highlighting.md
> +  teaser: "assets/images/devo-theme/hero_bg.jpg"
Thanks @tripu for reviewing ;) Regarding the content width issue, I have preferred to keep the blog's default implementation, bearing in mind that the default width in the big-screens break-point is what other sites like "Medium" usually use.

Also, we have to bear in mind that if you include: "classes: wide" in the props of your post, the content will automatically occupy all the available width.

Therefore, all you have to do is include this property in those posts that you want to occupy all the horizontal space available (look at the example post whose title is "" Wide Single Layout Page "")

2021-04-16 09:35 UTC, tripu commented on _posts/2013-08-16-markup-syntax-highlighting.md
> +  teaser: "assets/images/devo-theme/hero_bg.jpg"
Ah! Great, I didn't realise of that. Perfect, then!

2021-04-16 09:37 UTC, tripu approved these changes
LGTM now!

2021-04-19 06:02 UTC, merged